/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layout;

import java.awt.CardLayout;

/**
 *
 * @author ASUS
 */
public class PilihGambarComboBox extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pilihanCMB = new javax.swing.JComboBox<>();
        imagePanel = new javax.swing.JPanel();
        Glassfish = new javax.swing.JLabel();
        JavaEE = new javax.swing.JLabel();
        PostgreSQL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("Pilih Gambar");
        ButtonPanel1.add(jLabel1);

        pilihanCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Glassfish", "JavaEE", "PostgreSQL" }));
        pilihanCMB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pilihanCMBItemStateChanged(evt);
            }
        });
        ButtonPanel1.add(pilihanCMB);

        getContentPane().add(ButtonPanel1, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        Glassfish.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Glassfish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Layout/c.jpg"))); // NOI18N
        imagePanel.add(Glassfish, "0");

        JavaEE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JavaEE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Layout/download.jpg"))); // NOI18N
        imagePanel.add(JavaEE, "1");

        PostgreSQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Layout/download (1).jpg"))); // NOI18N
        imagePanel.add(PostgreSQL, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihanCMBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pilihanCMBItemStateChanged
        // TODO add your handling code here:
        if(pilihanCMB.getSelectedItem().equals("Glassfish")){
            CardLayout cl = (CardLayout)(imagePanel.getLayout());
            cl.show(imagePanel, "0");
        }else
            if(pilihanCMB.getSelectedItem().equals("JavaEE")){
            CardLayout cl = (CardLayout)(imagePanel.getLayout());
            cl.show(imagePanel, "1");
        }else
                if(pilihanCMB.getSelectedItem().equals("PostgreSQL")){
            CardLayout cl = (CardLayout)(imagePanel.getLayout());
            cl.show(imagePanel, "2");
        }
      
    }//GEN-LAST:event_pilihanCMBItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel1;
    private javax.swing.JLabel Glassfish;
    private javax.swing.JLabel JavaEE;
    private javax.swing.JLabel PostgreSQL;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> pilihanCMB;
    // End of variables declaration//GEN-END:variables
}
